---
title: "Untitled"
author: "Shelby Smith"
date: "9/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(RColorBrewer)
library(rgeos)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(spData)
library(spDataLarge)
library(tidyverse)
library(tmap)
library(raster)
library(ncdf4)
library(here)
library(marmap)
library(rgdal)
library(mapproj)
```

```{r fig.height=5.5, fig.width=4}
nz<-- getNOAA.bathy(
  lon1=165,
  lon2= 180,
  lat1= -33,
  lat2=-50,
  resolution = 1
)

blues <- c("lightsteelblue4", "lightsteelblue3",
           "lightsteelblue2", "lightsteelblue1")
greys <- c(grey(0.6), grey(0.93), grey(0.99))
plot(nz, image = TRUE, land = TRUE, lwd = 0.03,
     bpal = list(c(0, max(nz), blues),
                 c(min(nz), 0, greys)))
# Add coastline
plot(nz, n = 1, lwd = 0.4, add = TRUE)
```

```{r}
autoplot.bathy(nz, geom=c("tile","contour")) +
    scale_fill_gradient2(low="dodgerblue4", mid="gainsboro", high="darkgreen") +
    labs(y = "Latitude", x = "Longitude", fill = "Elevation") +
    coord_cartesian(expand = 0)+
    ggtitle("A marmap map with ggplot2") 
```

